#!/usr/bin/env node

/**
 * Build Configuration Script
 * Generates app/chat/config.js from environment variables
 * 
 * Run: node build-config.js
 * Or automatically via npm predev/prebuild scripts
 */

const fs = require('fs');
const path = require('path');

// Load .env file if it exists (for local development)
const envPath = path.join(__dirname, '.env');
if (fs.existsSync(envPath)) {
  const envContent = fs.readFileSync(envPath, 'utf-8');
  envContent.split('\n').forEach(line => {
    const trimmed = line.trim();
    if (trimmed && !trimmed.startsWith('#')) {
      const [key, ...valueParts] = trimmed.split('=');
      if (key && valueParts.length > 0) {
        const value = valueParts.join('=').trim();
        // Remove quotes if present
        process.env[key.trim()] = value.replace(/^["']|["']$/g, '');
      }
    }
  });
}

// Get API key from environment
const apiKey = process.env.OPENROUTER_API_KEY || '';

if (!apiKey) {
  console.warn('\x1b[33m⚠ Warning: OPENROUTER_API_KEY not set in environment.\x1b[0m');
  console.warn('  Users will need to enter their API key in the chat settings.');
  console.warn('  Set OPENROUTER_API_KEY in .env or environment variables.\n');
}

// Configuration content
const configContent = `/**
 * Application Configuration
 * Auto-generated by build-config.js - DO NOT EDIT MANUALLY
 * 
 * To update, modify environment variables and run: node build-config.js
 */

const CONFIG = {
    // OpenRouter API Key (from environment)
    OPENROUTER_API_KEY: '${apiKey}',
    
    // Available Models
    MODELS: [
        {
            id: 'x-ai/grok-4.1-fast',
            name: 'Grok 4.1 Fast',
            context: '2M',
            description: 'Ultra-fast model with massive 2M context window',
            isDefault: true
        },
        {
            id: 'google/gemini-2.0-flash-001',
            name: 'Gemini 2.0 Flash',
            context: '1M',
            description: 'Fast model with large context window'
        },
        {
            id: 'anthropic/claude-3.5-sonnet',
            name: 'Claude 3.5 Sonnet',
            context: '200K',
            description: 'High quality reasoning'
        },
        {
            id: 'openai/gpt-4o-mini',
            name: 'GPT-4o Mini',
            context: '128K',
            description: 'Fast and affordable'
        }
    ],
    
    // Get default model
    getDefaultModel() {
        return this.MODELS.find(m => m.isDefault) || this.MODELS[0];
    }
};

window.APP_CONFIG = CONFIG;
`;

// Write to public/chat/config.js (for static serving)
const outputPath = path.join(__dirname, 'public', 'chat', 'config.js');
fs.writeFileSync(outputPath, configContent, 'utf-8');

console.log('\x1b[32m✓ Generated public/chat/config.js\x1b[0m');
if (apiKey) {
  console.log('  API key: ' + apiKey.substring(0, 10) + '...[hidden]');
} else {
  console.log('  API key: (not configured)');
}
console.log('  Default model: x-ai/grok-4.1-fast (2M context)\n');
