/**
 * Japanese translations for infographic labels (Kajima Mode)
 * 
 * Consulting-grade Japanese suitable for McKinsey/BCG/Kajima presentations
 */

export const jaLabels = {
  // Headers & Titles
  recommendation: '推奨方針',
  investmentInfographic: '投資分析レポート',
  confidence: '確信度',
  
  // VerdictCard
  tellItToMeStraight: '結論',
  keyTakeaways: '重要ポイント',
  
  // SixTRadar / FiveTRadar
  sixTRiskAnalysis: 'Six-Tリスク分析',
  fiveTRiskAnalysis: 'Five-Tリスク分析',
  team: 'チーム',
  tam: 'TAM',
  technology: 'テクノロジー',
  traction: 'トラクション',
  terms: '条件',
  trends: 'トレンド',
  lowRisk: '低リスク',
  mediumRisk: '中リスク',
  highRisk: '高リスク',
  
  // HighlightCards
  keyHighlights: '主要ハイライト',
  
  // AssumptionsList
  criticalAssumptions: '重要な前提条件',
  assumptionsSubtitle: '本投資の成功に必要な前提条件',
  validated: '検証済み',
  pending: '検証中',
  atRisk: 'リスクあり',
  
  // VerdictPair
  investmentAssessment: '投資評価',
  shouldWeDoIt: '実行すべきか？',
  canWeDoIt: '実行可能か？',
  supportingFactors: '根拠',
  
  // NextStepsTimeline
  recommendedNextSteps: '推奨アクション',
  successGate: '成功基準',
  
  // ChapterSummaries
  detailedAnalysis: '詳細分析',
  teamAnalysis: 'チーム分析',
  opportunityValidation: '市場機会の検証',
  pathToSuccess: '成功への道筋',
  operations: 'オペレーション',
  
  // Chapter subsections
  capabilityAssessment: '能力評価',
  identifiedGaps: '課題・ギャップ',
  supportingData: '根拠データ',
  problemStatement: '課題定義',
  marketSize: '市場規模',
  competitivePositioning: '競争ポジショニング',
  productRequirements: '製品要件',
  goToMarket: '市場参入戦略',
  revenueModel: '収益モデル',
  irr: 'IRR',
  paybackPeriod: '回収期間',
  margins: 'マージン',
  operationalRisks: 'オペレーショナルリスク',
  
  // ExecutiveNarrative
  executiveNarrative: 'エグゼクティブサマリー',
  
  // Strategic Fit
  strategicFitAssessment: '戦略適合性評価',
  highConfidence: '高確信度',
  mediumConfidence: '中確信度',
  lowConfidence: '低確信度',
  
  // Footer
  generatedBy: 'The Olsenator — Innovera 投資分析プラットフォームにより生成',
  
  // Decisions
  proceed: '承認',
  doNotProceed: '非承認',
  conditional: '条件付き承認',
} as const;

export const enLabels = {
  // Headers & Titles
  recommendation: 'RECOMMENDATION',
  investmentInfographic: 'Investment Infographic',
  confidence: 'Confidence',
  
  // VerdictCard
  tellItToMeStraight: 'Tell It To Me Straight',
  keyTakeaways: 'KEY TAKEAWAYS',
  
  // SixTRadar / FiveTRadar
  sixTRiskAnalysis: 'Six-T Risk Analysis',
  fiveTRiskAnalysis: 'Five-T Risk Analysis',
  team: 'Team',
  tam: 'TAM',
  technology: 'Technology',
  traction: 'Traction',
  terms: 'Terms',
  trends: 'Trends',
  lowRisk: 'Low Risk',
  mediumRisk: 'Medium Risk',
  highRisk: 'High Risk',
  
  // HighlightCards
  keyHighlights: 'Key Highlights',
  
  // AssumptionsList
  criticalAssumptions: 'Critical Assumptions',
  assumptionsSubtitle: 'What you would have to believe for this investment to succeed',
  validated: 'Validated',
  pending: 'Pending',
  atRisk: 'At Risk',
  
  // VerdictPair
  investmentAssessment: 'Investment Assessment',
  shouldWeDoIt: 'Should We Do It?',
  canWeDoIt: 'Can We Do It?',
  supportingFactors: 'SUPPORTING FACTORS',
  
  // NextStepsTimeline
  recommendedNextSteps: 'Recommended Next Steps',
  successGate: 'Success Gate',
  
  // ChapterSummaries
  detailedAnalysis: 'Detailed Analysis',
  teamAnalysis: 'Team Analysis',
  opportunityValidation: 'Opportunity Validation',
  pathToSuccess: 'Path to Success',
  operations: 'Operations',
  
  // Chapter subsections
  capabilityAssessment: 'Capability Assessment',
  identifiedGaps: 'Identified Gaps',
  supportingData: 'Supporting Data',
  problemStatement: 'Problem Statement',
  marketSize: 'Market Size',
  competitivePositioning: 'Competitive Positioning',
  productRequirements: 'Product Requirements',
  goToMarket: 'Go-to-Market',
  revenueModel: 'Revenue Model',
  irr: 'IRR',
  paybackPeriod: 'Payback Period',
  margins: 'Margins',
  operationalRisks: 'Operational Risks',
  
  // ExecutiveNarrative
  executiveNarrative: 'Executive Narrative',
  
  // Strategic Fit
  strategicFitAssessment: 'Strategic Fit Assessment',
  highConfidence: 'High Confidence',
  mediumConfidence: 'Medium Confidence',
  lowConfidence: 'Low Confidence',
  
  // Footer
  generatedBy: 'Generated by The Olsenator — Innovera Investment Analysis Platform',
  
  // Decisions
  proceed: 'Proceed',
  doNotProceed: 'Do Not Proceed',
  conditional: 'Conditional',
} as const;

export type LabelKey = keyof typeof enLabels;

/**
 * Get labels based on Kajima mode
 */
export function getLabels(kajimaMode: boolean): typeof enLabels | typeof jaLabels {
  return kajimaMode ? jaLabels : enLabels;
}

/**
 * Get a specific label
 */
export function getLabel(key: LabelKey, kajimaMode: boolean): string {
  return kajimaMode ? jaLabels[key] : enLabels[key];
}

