import { ExtractionResult, validateExtractionResult } from './schema';
import { QAExtractionResult, validateQAExtractionResult } from './qa-schema';
import { V2ExtractionResult, validateV2ExtractionResult } from './v2-schema';
import { EXTRACTION_SYSTEM_PROMPT, SIMPLIFIED_EXTRACTION_PROMPT, createUserPrompt } from './prompts';
import { QA_EXTRACTION_SYSTEM_PROMPT, SIMPLIFIED_QA_EXTRACTION_PROMPT, createQAUserPrompt } from './qa-prompts';
import { JSON_CLEANUP_PROMPT, createV2UserPrompt } from './v2-prompts';

const OPENROUTER_API_URL = 'https://openrouter.ai/api/v1/chat/completions';
const MODEL = 'google/gemini-3-flash-preview';

interface OpenRouterMessage {
  role: 'system' | 'user' | 'assistant';
  content: string;
}

interface OpenRouterResponse {
  id: string;
  choices: {
    message: {
      content: string;
    };
    finish_reason: string;
  }[];
  error?: {
    message: string;
    code: string;
  };
}

export interface ExtractionResponse {
  success: boolean;
  data?: ExtractionResult;
  error?: string;
  retried?: boolean;
}

export interface QAExtractionResponse {
  success: boolean;
  data?: QAExtractionResult;
  error?: string;
  retried?: boolean;
}

export interface V2ExtractionResponse {
  success: boolean;
  data?: V2ExtractionResult;
  error?: string;
  retried?: boolean;
}

function extractJsonFromResponse(content: string): string {
  const jsonBlockMatch = content.match(/```(?:json)?\s*([\s\S]*?)```/);
  if (jsonBlockMatch) {
    return jsonBlockMatch[1].trim();
  }
  
  const jsonMatch = content.match(/\{[\s\S]*\}/);
  if (jsonMatch) {
    return jsonMatch[0];
  }
  
  return content.trim();
}

async function callOpenRouter(
  messages: OpenRouterMessage[],
  apiKey: string
): Promise<{ content: string; error?: string }> {
  try {
    const response = await fetch(OPENROUTER_API_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`,
        'HTTP-Referer': 'https://olsenator.vercel.app',
        'X-Title': 'The Olsenator',
      },
      body: JSON.stringify({
        model: MODEL,
        messages,
        temperature: 0.1,
        max_tokens: 8192,
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('OpenRouter API error:', response.status, errorText);
      return {
        content: '',
        error: `API request failed with status ${response.status}: ${errorText}`,
      };
    }

    const data: OpenRouterResponse = await response.json();

    if (data.error) {
      return {
        content: '',
        error: `OpenRouter error: ${data.error.message}`,
      };
    }

    if (!data.choices || data.choices.length === 0) {
      return {
        content: '',
        error: 'No response generated by the model',
      };
    }

    return {
      content: data.choices[0].message.content,
    };
  } catch (error) {
    console.error('OpenRouter request failed:', error);
    return {
      content: '',
      error: error instanceof Error ? error.message : 'Unknown error occurred',
    };
  }
}

function parseExtractionResult(content: string): { data?: ExtractionResult; error?: string } {
  try {
    const jsonContent = extractJsonFromResponse(content);
    const parsed = JSON.parse(jsonContent);
    
    if (!validateExtractionResult(parsed)) {
      return { error: 'Response does not match expected schema structure' };
    }
    
    return { data: parsed as ExtractionResult };
  } catch (error) {
    console.error('JSON parse error:', error);
    return { 
      error: error instanceof Error ? `Invalid JSON: ${error.message}` : 'Failed to parse JSON' 
    };
  }
}

function parseQAExtractionResult(content: string): { data?: QAExtractionResult; error?: string } {
  try {
    const jsonContent = extractJsonFromResponse(content);
    const parsed = JSON.parse(jsonContent);
    
    if (!validateQAExtractionResult(parsed)) {
      return { error: 'Response does not match expected Q&A schema structure' };
    }
    
    return { data: parsed as QAExtractionResult };
  } catch (error) {
    console.error('JSON parse error:', error);
    return { 
      error: error instanceof Error ? `Invalid JSON: ${error.message}` : 'Failed to parse JSON' 
    };
  }
}

export async function extractMemoData(
  memoContent: string,
  apiKey: string
): Promise<ExtractionResponse> {
  if (!memoContent.trim()) {
    return { success: false, error: 'Memo content cannot be empty' };
  }

  if (!apiKey) {
    return { success: false, error: 'OpenRouter API key is not configured' };
  }

  const messages: OpenRouterMessage[] = [
    { role: 'system', content: EXTRACTION_SYSTEM_PROMPT },
    { role: 'user', content: createUserPrompt(memoContent) },
  ];

  console.log('Attempting extraction with full prompt...');
  const firstResponse = await callOpenRouter(messages, apiKey);

  if (firstResponse.error) {
    return { success: false, error: firstResponse.error };
  }

  const firstParse = parseExtractionResult(firstResponse.content);
  if (firstParse.data) {
    return { success: true, data: firstParse.data };
  }

  console.log('First attempt failed, retrying with simplified prompt...');
  console.log('First attempt error:', firstParse.error);

  const retryMessages: OpenRouterMessage[] = [
    { role: 'system', content: SIMPLIFIED_EXTRACTION_PROMPT },
    { role: 'user', content: createUserPrompt(memoContent) },
  ];

  const retryResponse = await callOpenRouter(retryMessages, apiKey);

  if (retryResponse.error) {
    return { success: false, error: `Retry failed: ${retryResponse.error}`, retried: true };
  }

  const retryParse = parseExtractionResult(retryResponse.content);
  if (retryParse.data) {
    return { success: true, data: retryParse.data, retried: true };
  }

  return {
    success: false,
    error: `Failed to extract valid JSON after retry. Last error: ${retryParse.error}`,
    retried: true,
  };
}

export async function extractQAData(
  qaContent: string,
  apiKey: string
): Promise<QAExtractionResponse> {
  if (!qaContent.trim()) {
    return { success: false, error: 'Q&A content cannot be empty' };
  }

  if (!apiKey) {
    return { success: false, error: 'OpenRouter API key is not configured' };
  }

  const messages: OpenRouterMessage[] = [
    { role: 'system', content: QA_EXTRACTION_SYSTEM_PROMPT },
    { role: 'user', content: createQAUserPrompt(qaContent) },
  ];

  console.log('Attempting Q&A extraction with full prompt...');
  const firstResponse = await callOpenRouter(messages, apiKey);

  if (firstResponse.error) {
    return { success: false, error: firstResponse.error };
  }

  const firstParse = parseQAExtractionResult(firstResponse.content);
  if (firstParse.data) {
    return { success: true, data: firstParse.data };
  }

  console.log('First Q&A attempt failed, retrying with simplified prompt...');
  console.log('First attempt error:', firstParse.error);

  const retryMessages: OpenRouterMessage[] = [
    { role: 'system', content: SIMPLIFIED_QA_EXTRACTION_PROMPT },
    { role: 'user', content: createQAUserPrompt(qaContent) },
  ];

  const retryResponse = await callOpenRouter(retryMessages, apiKey);

  if (retryResponse.error) {
    return { success: false, error: `Retry failed: ${retryResponse.error}`, retried: true };
  }

  const retryParse = parseQAExtractionResult(retryResponse.content);
  if (retryParse.data) {
    return { success: true, data: retryParse.data, retried: true };
  }

  return {
    success: false,
    error: `Failed to extract valid Q&A JSON after retry. Last error: ${retryParse.error}`,
    retried: true,
  };
}

function parseV2ExtractionResult(content: string): { data?: V2ExtractionResult; error?: string } {
  try {
    const jsonContent = extractJsonFromResponse(content);
    const parsed = JSON.parse(jsonContent);
    
    if (!validateV2ExtractionResult(parsed)) {
      return { error: 'Response does not match expected V2 schema structure' };
    }
    
    return { data: parsed as V2ExtractionResult };
  } catch (error) {
    console.error('JSON parse error:', error);
    return { 
      error: error instanceof Error ? `Invalid JSON: ${error.message}` : 'Failed to parse JSON' 
    };
  }
}

export async function extractV2Data(
  documentContent: string,
  apiKey: string
): Promise<V2ExtractionResponse> {
  if (!documentContent.trim()) {
    return { success: false, error: 'Document content cannot be empty' };
  }

  if (!apiKey) {
    return { success: false, error: 'OpenRouter API key is not configured' };
  }

  const messages: OpenRouterMessage[] = [
    { role: 'system', content: JSON_CLEANUP_PROMPT },
    { role: 'user', content: createV2UserPrompt(documentContent) },
  ];

  console.log('Attempting JSON validation...');
  const response = await callOpenRouter(messages, apiKey);

  if (response.error) {
    return { success: false, error: response.error };
  }

  const parse = parseV2ExtractionResult(response.content);
  if (parse.data) {
    return { success: true, data: parse.data };
  }

  return {
    success: false,
    error: `Failed to validate JSON. Error: ${parse.error}`,
  };
}
