import { ExtractionResult, validateExtractionResult } from './schema';
import { EXTRACTION_SYSTEM_PROMPT, SIMPLIFIED_EXTRACTION_PROMPT, createUserPrompt } from './prompts';

const OPENROUTER_API_URL = 'https://openrouter.ai/api/v1/chat/completions';
const MODEL = 'google/gemini-2.5-pro-preview';

interface OpenRouterMessage {
  role: 'system' | 'user' | 'assistant';
  content: string;
}

interface OpenRouterResponse {
  id: string;
  choices: {
    message: {
      content: string;
    };
    finish_reason: string;
  }[];
  error?: {
    message: string;
    code: string;
  };
}

export interface ExtractionResponse {
  success: boolean;
  data?: ExtractionResult;
  error?: string;
  retried?: boolean;
}

/**
 * Extracts JSON from a response that might contain markdown code blocks
 */
function extractJsonFromResponse(content: string): string {
  // Try to extract JSON from markdown code blocks
  const jsonBlockMatch = content.match(/```(?:json)?\s*([\s\S]*?)```/);
  if (jsonBlockMatch) {
    return jsonBlockMatch[1].trim();
  }
  
  // Try to find raw JSON object
  const jsonMatch = content.match(/\{[\s\S]*\}/);
  if (jsonMatch) {
    return jsonMatch[0];
  }
  
  return content.trim();
}

/**
 * Calls OpenRouter API with the given messages
 */
async function callOpenRouter(
  messages: OpenRouterMessage[],
  apiKey: string
): Promise<{ content: string; error?: string }> {
  try {
    const response = await fetch(OPENROUTER_API_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`,
        'HTTP-Referer': 'https://olsenator.vercel.app',
        'X-Title': 'The Olsenator',
      },
      body: JSON.stringify({
        model: MODEL,
        messages,
        temperature: 0.1, // Low temperature for consistent extraction
        max_tokens: 8192,
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('OpenRouter API error:', response.status, errorText);
      return {
        content: '',
        error: `API request failed with status ${response.status}: ${errorText}`,
      };
    }

    const data: OpenRouterResponse = await response.json();

    if (data.error) {
      return {
        content: '',
        error: `OpenRouter error: ${data.error.message}`,
      };
    }

    if (!data.choices || data.choices.length === 0) {
      return {
        content: '',
        error: 'No response generated by the model',
      };
    }

    return {
      content: data.choices[0].message.content,
    };
  } catch (error) {
    console.error('OpenRouter request failed:', error);
    return {
      content: '',
      error: error instanceof Error ? error.message : 'Unknown error occurred',
    };
  }
}

/**
 * Attempts to parse and validate the extraction result
 */
function parseExtractionResult(content: string): { data?: ExtractionResult; error?: string } {
  try {
    const jsonContent = extractJsonFromResponse(content);
    const parsed = JSON.parse(jsonContent);
    
    if (!validateExtractionResult(parsed)) {
      return { error: 'Response does not match expected schema structure' };
    }
    
    return { data: parsed as ExtractionResult };
  } catch (error) {
    console.error('JSON parse error:', error);
    return { 
      error: error instanceof Error ? `Invalid JSON: ${error.message}` : 'Failed to parse JSON' 
    };
  }
}

/**
 * Main extraction function - extracts structured data from an investment memo
 * 
 * @param memoContent - The raw investment memo text
 * @param apiKey - OpenRouter API key
 * @returns ExtractionResponse with success status and data or error
 */
export async function extractMemoData(
  memoContent: string,
  apiKey: string
): Promise<ExtractionResponse> {
  if (!memoContent.trim()) {
    return {
      success: false,
      error: 'Memo content cannot be empty',
    };
  }

  if (!apiKey) {
    return {
      success: false,
      error: 'OpenRouter API key is not configured',
    };
  }

  // First attempt with full prompt
  const messages: OpenRouterMessage[] = [
    { role: 'system', content: EXTRACTION_SYSTEM_PROMPT },
    { role: 'user', content: createUserPrompt(memoContent) },
  ];

  console.log('Attempting extraction with full prompt...');
  const firstResponse = await callOpenRouter(messages, apiKey);

  if (firstResponse.error) {
    return {
      success: false,
      error: firstResponse.error,
    };
  }

  // Try to parse first response
  const firstParse = parseExtractionResult(firstResponse.content);
  if (firstParse.data) {
    return {
      success: true,
      data: firstParse.data,
    };
  }

  // Retry with simplified prompt
  console.log('First attempt failed, retrying with simplified prompt...');
  console.log('First attempt error:', firstParse.error);

  const retryMessages: OpenRouterMessage[] = [
    { role: 'system', content: SIMPLIFIED_EXTRACTION_PROMPT },
    { role: 'user', content: createUserPrompt(memoContent) },
  ];

  const retryResponse = await callOpenRouter(retryMessages, apiKey);

  if (retryResponse.error) {
    return {
      success: false,
      error: `Retry failed: ${retryResponse.error}`,
      retried: true,
    };
  }

  const retryParse = parseExtractionResult(retryResponse.content);
  if (retryParse.data) {
    return {
      success: true,
      data: retryParse.data,
      retried: true,
    };
  }

  return {
    success: false,
    error: `Failed to extract valid JSON after retry. Last error: ${retryParse.error}`,
    retried: true,
  };
}

