// UI translations for V2 Infographic components

export type Language = 'en' | 'ja';

export const translations = {
  // V2InfographicContainer
  executiveInfographic: {
    en: 'V2 Executive Infographic',
    ja: 'V2 エグゼクティブインフォグラフィック'
  },
  copyHtml: {
    en: 'Copy HTML',
    ja: 'HTMLをコピー'
  },
  downloadPdf: {
    en: 'Download as PDF',
    ja: 'PDFとしてダウンロード'
  },
  generatedBy: {
    en: 'Generated by The Olsenator V2',
    ja: 'The Olsenator V2 により生成'
  },

  // BannerSection
  stage: {
    en: 'Stage',
    ja: 'ステージ'
  },
  sector: {
    en: 'Sector',
    ja: 'セクター'
  },
  geography: {
    en: 'Geography',
    ja: '地域'
  },
  date: {
    en: 'Date',
    ja: '日付'
  },
  theVerdict: {
    en: 'The Verdict',
    ja: '結論'
  },
  thePrize: {
    en: 'The Prize',
    ja: '獲得機会'
  },
  theRisk: {
    en: 'The Risk',
    ja: 'リスク'
  },
  theUnlock: {
    en: 'The Unlock',
    ja: '解決の鍵'
  },
  go: {
    en: 'Go',
    ja: 'Go'
  },
  noGo: {
    en: 'No Go',
    ja: 'No Go'
  },
  conditionalGo: {
    en: 'Conditional Go',
    ja: '条件付きGo'
  },
  conditional: {
    en: 'Conditional',
    ja: '条件付き'
  },

  // NextStepsPathway
  nextSteps: {
    en: 'Next Steps',
    ja: '次のステップ'
  },
  phase1Validation: {
    en: 'Phase 1: Validation',
    ja: 'フェーズ1：検証'
  },
  phase2Execution: {
    en: 'Phase 2: Execution',
    ja: 'フェーズ2：実行'
  },
  ifAllGatesPass: {
    en: 'If All Gates Pass',
    ja: '全てのゲートを通過した場合'
  },
  successGate: {
    en: 'Success Gate',
    ja: '成功ゲート'
  },
  whatToDo: {
    en: 'What to do',
    ja: '実施内容'
  },
  unlocks: {
    en: 'Unlocks',
    ja: '解除される項目'
  },
  ifGateFails: {
    en: 'If Gate Fails',
    ja: 'ゲート失敗時'
  },
  venture: {
    en: 'venture',
    ja: 'ベンチャー'
  },
  joint: {
    en: 'joint',
    ja: '共同'
  },
  investor: {
    en: 'investor',
    ja: '投資家'
  },

  // ProcessSection
  pathSelectionAnalysis: {
    en: 'Path Selection Analysis',
    ja: '戦略パス選定分析'
  },
  recommended: {
    en: 'Recommended',
    ja: '推奨'
  },
  option1PartnershipLed: {
    en: 'Option 1: Partnership-Led',
    ja: 'オプション1：提携主導'
  },
  option1Description: {
    en: 'Focus on Steps 2–3 (Inspection/Design) while partnering for Step 1.',
    ja: 'ステップ2〜3（点検／設計）に集中し、ステップ1は提携で補完。'
  },
  option2FullInternalBuild: {
    en: 'Option 2: Full Internal Build',
    ja: 'オプション2：内製フル構築'
  },
  option2Description: {
    en: 'Build proprietary "Super-App" covering entire lifecycle (Steps 1–5).',
    ja: '全工程（ステップ1〜5）を網羅する独自「スーパーアプリ」を構築。'
  },
  option3Acquisition: {
    en: 'Option 3: Acquisition',
    ja: 'オプション3：買収'
  },
  option3Description: {
    en: 'Acquire a GovTech startup to secure tech stack and user base immediately.',
    ja: 'GovTechスタートアップを買収し、技術スタックとユーザーベースを即時確保。'
  },
  viewDetailsStrategy: {
    en: 'View Details & Strategy',
    ja: '詳細・戦略を見る'
  },
  viewAnalysis: {
    en: 'View Analysis',
    ja: '分析を見る'
  },
  whyRejected: {
    en: 'Why Rejected',
    ja: '却下理由'
  },
  recommendation: {
    en: 'Recommendation',
    ja: '推奨方針'
  },
  strategy: {
    en: 'Strategy',
    ja: '戦略'
  },
  pros: {
    en: 'Pros',
    ja: 'メリット'
  },
  cons: {
    en: 'Cons',
    ja: 'デメリット'
  },
  option1StrategyDetail: {
    en: 'Integrate with an existing civic-tech player like Dappi Studio LLC (FixMyStreet Japan) via API to handle citizen reporting. NLM builds the downstream workflow engine that converts these reports into professional engineering tasks.',
    ja: 'Dappi Studio LLC（FixMyStreet Japan）など既存のシビックテックとAPI連携し、市民通報を取り込む。NLMは通報を専門エンジニアリング業務に変換する下流ワークフローを構築。'
  },
  option1ConsDetail: {
    en: 'Creates dependency on third-party roadmaps; requires successful API integration negotiation.',
    ja: '第三者の開発ロードマップに依存し、API連携交渉の成立が前提となる。'
  },
  recommendedEngagementModel: {
    en: 'Recommended Engagement Model',
    ja: '推奨関与モデル'
  },
  leadUnit: {
    en: 'Lead Unit',
    ja: '主担当'
  },
  leadUnitDetail: {
    en: 'New Business Planning & Strategy Division acts as the "Venture Lead," responsible for the platform business model.',
    ja: '新規事業企画・戦略部門が「ベンチャーリード」としてプラットフォーム事業モデルを担う。'
  },
  domainExpert: {
    en: 'Domain Expert',
    ja: 'ドメイン専門家'
  },
  domainExpertDetail: {
    en: 'Nikkei Engineering acts as the "Technical Anchor," defining the inspection protocols (Steps 2–3).',
    ja: '日経エンジニアリングが「技術アンカー」として点検プロトコル（ステップ2〜3）を定義。'
  },
  orchestrationRole: {
    en: 'Orchestration Role',
    ja: 'オーケストレーション役'
  },
  orchestrationRoleDetail: {
    en: 'NLM functions as the Platform Orchestrator, managing the data flow between citizens, municipalities, and external contractors.',
    ja: 'NLMがプラットフォーム・オーケストレーターとして、市民・自治体・外部事業者間のデータ流通を統括。'
  },
  option1ModalTitle: {
    en: 'Option 1: Partnership-Led Narrow Platform',
    ja: 'オプション1：提携主導のナロープラットフォーム'
  },
  option2ModalTitle: {
    en: 'Option 2: Full Internal Build',
    ja: 'オプション2：内製フル構築'
  },
  option3ModalTitle: {
    en: 'Option 3: Strategic Acquisition',
    ja: 'オプション3：戦略的買収'
  },
  option2StrategyDetail: {
    en: 'Build a closed ecosystem where NLM owns all data and user interfaces. Develop a proprietary "Super-App" covering the entire lifecycle from citizen reporting to construction management (Steps 1–5).',
    ja: 'NLMがデータとUIを全て保有するクローズドなエコシステムを構築。市民通報から施工管理まで全工程（ステップ1〜5）を担う独自「スーパーアプリ」を開発。'
  },
  option2ProsDetail: {
    en: 'Maximum control over data security and user experience; eliminates vendor dependencies.',
    ja: 'データセキュリティとUXを最大限に統制でき、ベンダー依存を排除。'
  },
  option2ConsDetail: {
    en: 'Custom software development involves significant upfront costs and maintenance liabilities.',
    ja: '独自ソフト開発には多額の初期投資と維持負担が伴う。'
  },
  option2RedundancyTitle: {
    en: 'Redundancy',
    ja: '冗長性'
  },
  option2RedundancyDetail: {
    en: 'Replicates existing free tools (e.g., LINE reporting, FixMyStreet), potentially slowing municipal adoption due to switching costs.',
    ja: '既存の無料ツール（例：LINE通報、FixMyStreet）と重複し、乗り換えコストが自治体導入の障壁となり得る。'
  },
  option3StrategyDetail: {
    en: 'Acquire a player like Dappi Studio LLC to own the "Step 1" entry point. Immediately secure the technology stack and user base.',
    ja: 'Dappi Studio LLCのようなプレイヤーを買収し、「ステップ1」の入口を確保。技術スタックとユーザーベースを即時取得。'
  },
  option3ProsDetail: {
    en: 'Immediate market share and talent acquisition.',
    ja: '市場シェアと人材を即時獲得。'
  },
  option3ConsDetail: {
    en: 'GovTech valuations are rising, with multiples reaching high double-digits.',
    ja: 'GovTechの評価倍率は高騰しており、二桁後半のマルチプルに達している。'
  },
  option3IntegrationRiskTitle: {
    en: 'Integration Risk',
    ja: '統合リスク'
  },
  option3IntegrationRiskDetail: {
    en: 'Cultural mismatch between a nimble civic-tech startup and a large corporate entity could stifle innovation.',
    ja: '俊敏なシビックテック企業と大企業の文化不一致が、イノベーションを阻害する可能性。'
  },

  // StrategicFitSection
  strategicFitAssessment: {
    en: 'Strategic Fit Assessment',
    ja: '戦略的適合性評価'
  },
  strategicAttractiveness: {
    en: 'Strategic Attractiveness',
    ja: '戦略的魅力度'
  },
  executionCapability: {
    en: 'Execution Capability',
    ja: '実行力'
  },
  capitalInfrastructure: {
    en: 'Capital & Infrastructure',
    ja: '資本・インフラ'
  },
  priorityAlignment: {
    en: 'Priority Alignment',
    ja: '優先事項の整合性'
  },
  strategicPosition: {
    en: 'Strategic Position',
    ja: '戦略的位置付け'
  },
  high: {
    en: 'High',
    ja: '高'
  },
  low: {
    en: 'Low',
    ja: '低'
  },
  executionAxis: {
    en: 'Execution',
    ja: '実行力'
  },
  capableButUninteresting: {
    en: 'Capable but\nUninteresting',
    ja: '実行可能だが魅力に欠ける'
  },
  highValueOpportunity: {
    en: 'High Value\nOpportunity',
    ja: '高価値の機会'
  },
  avoid: {
    en: 'Avoid',
    ja: '回避'
  },
  strategicButRisky: {
    en: 'Strategic\nbut Risky',
    ja: '戦略的だがリスク高'
  },
  thisVenture: {
    en: 'This Venture',
    ja: '本件'
  },
  shouldWeDoIt: {
    en: 'Should We Do It?',
    ja: '実施すべきか？'
  },
  canWeDoIt: {
    en: 'Can We Do It?',
    ja: '実施可能か？'
  },
  thePrizeLabel: {
    en: 'The Prize',
    ja: '獲得機会'
  },
  strategicFit: {
    en: 'Strategic Fit',
    ja: '戦略的適合性'
  },
  ourEdge: {
    en: 'Our Edge',
    ja: '競争優位性'
  },
  capital: {
    en: 'Capital',
    ja: '資本'
  },
  marketAccess: {
    en: 'Market Access',
    ja: '市場アクセス'
  },
  people: {
    en: 'People',
    ja: '人材'
  },
  marketSize: {
    en: 'Market Size',
    ja: '市場規模'
  },
  margins: {
    en: 'Margins',
    ja: '利益率'
  },
  durability: {
    en: 'Durability',
    ja: '持続性'
  },
  bottomLine: {
    en: 'Bottom Line',
    ja: '結論'
  },
  betType: {
    en: 'Bet Type',
    ja: '投資タイプ'
  },
  portfolioFit: {
    en: 'Portfolio Fit',
    ja: 'ポートフォリオ適合性'
  },
  policyAlignment: {
    en: 'Policy Alignment',
    ja: '政策整合性'
  },
  unfairAdvantages: {
    en: 'Unfair Advantages',
    ja: '圧倒的優位性'
  },
  whyUs: {
    en: 'Why Us',
    ja: 'なぜ我々か'
  },
  cashPosition: {
    en: 'Cash Position',
    ja: 'キャッシュポジション'
  },
  facilities: {
    en: 'Facilities',
    ja: '施設'
  },
  toolsSystems: {
    en: 'Tools & Systems',
    ja: 'ツール＆システム'
  },
  customerRelationships: {
    en: 'Customer Relationships',
    ja: '顧客関係'
  },
  geographicPresence: {
    en: 'Geographic Presence',
    ja: '地理的プレゼンス'
  },
  regulatoryExperience: {
    en: 'Regulatory Experience',
    ja: '規制対応経験'
  },
  skills: {
    en: 'Skills',
    ja: 'スキル'
  },
  experience: {
    en: 'Experience',
    ja: '経験'
  },
  bandwidth: {
    en: 'Bandwidth',
    ja: 'リソース余力'
  },
  verdict: {
    en: 'Verdict',
    ja: '評決'
  },
  yes: {
    en: 'Yes',
    ja: 'はい'
  },
  no: {
    en: 'No',
    ja: 'いいえ'
  },
  borderline: {
    en: 'Borderline',
    ja: '境界線上'
  },
  high: {
    en: 'High',
    ja: '高'
  },
  medium: {
    en: 'Medium',
    ja: '中'
  },
  low: {
    en: 'Low',
    ja: '低'
  },
  synthesis: {
    en: 'Synthesis',
    ja: '総括'
  },
  alignment: {
    en: 'Alignment',
    ja: '整合性'
  },
  divergence: {
    en: 'Divergence',
    ja: '乖離点'
  },
  gapToClose: {
    en: 'Gap to Close',
    ja: '埋めるべきギャップ'
  },
  finalVerdict: {
    en: 'Final Verdict',
    ja: '最終評決'
  },
  condition: {
    en: 'Condition',
    ja: '条件'
  },
  confidence: {
    en: 'Confidence',
    ja: '確信度'
  },

  // HighlightsV2Section
  keyHighlights: {
    en: 'Key Highlights',
    ja: '主要ハイライト'
  },
  tailwinds: {
    en: 'Tailwinds',
    ja: '追い風'
  },
  headwinds: {
    en: 'Headwinds',
    ja: '向かい風'
  },
  showDetails: {
    en: 'Show Details',
    ja: '詳細を表示'
  },
  hideDetails: {
    en: 'Hide Details',
    ja: '詳細を隠す'
  },
  whyItMatters: {
    en: 'Why It Matters',
    ja: '重要な理由'
  },
  context: {
    en: 'Context',
    ja: '背景'
  },
  timeBound: {
    en: 'Time-Bound',
    ja: '期限付き'
  },
  verified: {
    en: 'verified',
    ja: '検証済み'
  },
  estimated: {
    en: 'estimated',
    ja: '推定'
  },
  assumed: {
    en: 'assumed',
    ja: '想定'
  },

  // ProcessSection
  theProcess: {
    en: 'The Process',
    ja: 'プロセス'
  },
  recommendedPath: {
    en: 'Recommended Path',
    ja: '推奨パス'
  },
  keyTradeOffs: {
    en: 'Key Trade-offs',
    ja: '主要トレードオフ'
  },
  alternativesConsidered: {
    en: 'Alternatives Considered',
    ja: '検討された代替案'
  },
  pathAdvantages: {
    en: 'Path Advantages',
    ja: 'パスの利点'
  },
  testedInsights: {
    en: 'Tested Insights',
    ja: '検証済みインサイト'
  },
  acknowledgedRisks: {
    en: 'Acknowledged Risks',
    ja: '認識されたリスク'
  },
  severity: {
    en: 'Severity',
    ja: '深刻度'
  },
  showAllInsights: {
    en: 'Show All Insights',
    ja: '全てのインサイトを表示'
  },
  hideInsights: {
    en: 'Hide Insights',
    ja: 'インサイトを隠す'
  },

  // Failure actions
  pivot: {
    en: 'Pivot',
    ja: 'ピボット'
  },
  pass: {
    en: 'Pass',
    ja: 'パス'
  },
  reassess: {
    en: 'Reassess',
    ja: '再評価'
  }
};

export function t(key: keyof typeof translations, lang: Language): string {
  return translations[key][lang] || translations[key]['en'];
}

// Helper to format date based on language
export function formatDate(date: Date, lang: Language): string {
  if (lang === 'ja') {
    return date.toLocaleDateString('ja-JP', { year: 'numeric', month: 'long', day: 'numeric' });
  }
  return date.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
}

// Helper to format long date based on language
export function formatDateLong(date: Date, lang: Language): string {
  if (lang === 'ja') {
    return date.toLocaleDateString('ja-JP', { year: 'numeric', month: 'long', day: 'numeric' });
  }
  return date.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
}
