// UI translations for V2 Infographic components

export type Language = 'en' | 'ja';

export const translations = {
  // V2InfographicContainer
  executiveInfographic: {
    en: 'V2 Executive Infographic',
    ja: 'V2 エグゼクティブインフォグラフィック'
  },
  copyHtml: {
    en: 'Copy HTML',
    ja: 'HTMLをコピー'
  },
  downloadPdf: {
    en: 'Download as PDF',
    ja: 'PDFとしてダウンロード'
  },
  generatedBy: {
    en: 'Generated by The Olsenator V2',
    ja: 'The Olsenator V2 により生成'
  },

  // BannerSection
  stage: {
    en: 'Stage',
    ja: 'ステージ'
  },
  sector: {
    en: 'Sector',
    ja: 'セクター'
  },
  geography: {
    en: 'Geography',
    ja: '地域'
  },
  date: {
    en: 'Date',
    ja: '日付'
  },
  theVerdict: {
    en: 'The Verdict',
    ja: '結論'
  },
  thePrize: {
    en: 'The Prize',
    ja: '獲得機会'
  },
  theRisk: {
    en: 'The Risk',
    ja: 'リスク'
  },
  theUnlock: {
    en: 'The Unlock',
    ja: '解決の鍵'
  },
  go: {
    en: 'Go',
    ja: 'Go'
  },
  noGo: {
    en: 'No Go',
    ja: 'No Go'
  },
  conditionalGo: {
    en: 'Conditional Go',
    ja: '条件付きGo'
  },
  conditional: {
    en: 'Conditional',
    ja: '条件付き'
  },

  // NextStepsPathway
  nextSteps: {
    en: 'Next Steps',
    ja: '次のステップ'
  },
  phase1Validation: {
    en: 'Phase 1: Validation',
    ja: 'フェーズ1：検証'
  },
  phase2Execution: {
    en: 'Phase 2: Execution',
    ja: 'フェーズ2：実行'
  },
  ifAllGatesPass: {
    en: 'If All Gates Pass',
    ja: '全てのゲートを通過した場合'
  },
  successGate: {
    en: 'Success Gate',
    ja: '成功ゲート'
  },
  whatToDo: {
    en: 'What to do',
    ja: '実施内容'
  },
  unlocks: {
    en: 'Unlocks',
    ja: '解除される項目'
  },
  ifGateFails: {
    en: 'If Gate Fails',
    ja: 'ゲート失敗時'
  },
  venture: {
    en: 'venture',
    ja: 'ベンチャー'
  },
  joint: {
    en: 'joint',
    ja: '共同'
  },
  investor: {
    en: 'investor',
    ja: '投資家'
  },

  // StrategicFitSection
  strategicFitAssessment: {
    en: 'Strategic Fit Assessment',
    ja: '戦略的適合性評価'
  },
  shouldWeDoIt: {
    en: 'Should We Do It?',
    ja: '実施すべきか？'
  },
  canWeDoIt: {
    en: 'Can We Do It?',
    ja: '実施可能か？'
  },
  thePrizeLabel: {
    en: 'The Prize',
    ja: '獲得機会'
  },
  strategicFit: {
    en: 'Strategic Fit',
    ja: '戦略的適合性'
  },
  ourEdge: {
    en: 'Our Edge',
    ja: '競争優位性'
  },
  capital: {
    en: 'Capital',
    ja: '資本'
  },
  marketAccess: {
    en: 'Market Access',
    ja: '市場アクセス'
  },
  people: {
    en: 'People',
    ja: '人材'
  },
  marketSize: {
    en: 'Market Size',
    ja: '市場規模'
  },
  margins: {
    en: 'Margins',
    ja: '利益率'
  },
  durability: {
    en: 'Durability',
    ja: '持続性'
  },
  bottomLine: {
    en: 'Bottom Line',
    ja: '結論'
  },
  betType: {
    en: 'Bet Type',
    ja: '投資タイプ'
  },
  portfolioFit: {
    en: 'Portfolio Fit',
    ja: 'ポートフォリオ適合性'
  },
  policyAlignment: {
    en: 'Policy Alignment',
    ja: '政策整合性'
  },
  unfairAdvantages: {
    en: 'Unfair Advantages',
    ja: '圧倒的優位性'
  },
  whyUs: {
    en: 'Why Us',
    ja: 'なぜ我々か'
  },
  cashPosition: {
    en: 'Cash Position',
    ja: 'キャッシュポジション'
  },
  facilities: {
    en: 'Facilities',
    ja: '施設'
  },
  toolsSystems: {
    en: 'Tools & Systems',
    ja: 'ツール＆システム'
  },
  customerRelationships: {
    en: 'Customer Relationships',
    ja: '顧客関係'
  },
  geographicPresence: {
    en: 'Geographic Presence',
    ja: '地理的プレゼンス'
  },
  regulatoryExperience: {
    en: 'Regulatory Experience',
    ja: '規制対応経験'
  },
  skills: {
    en: 'Skills',
    ja: 'スキル'
  },
  experience: {
    en: 'Experience',
    ja: '経験'
  },
  bandwidth: {
    en: 'Bandwidth',
    ja: 'リソース余力'
  },
  verdict: {
    en: 'Verdict',
    ja: '評決'
  },
  yes: {
    en: 'Yes',
    ja: 'はい'
  },
  no: {
    en: 'No',
    ja: 'いいえ'
  },
  borderline: {
    en: 'Borderline',
    ja: '境界線上'
  },
  high: {
    en: 'High',
    ja: '高'
  },
  medium: {
    en: 'Medium',
    ja: '中'
  },
  low: {
    en: 'Low',
    ja: '低'
  },
  synthesis: {
    en: 'Synthesis',
    ja: '総括'
  },
  alignment: {
    en: 'Alignment',
    ja: '整合性'
  },
  divergence: {
    en: 'Divergence',
    ja: '乖離点'
  },
  gapToClose: {
    en: 'Gap to Close',
    ja: '埋めるべきギャップ'
  },
  finalVerdict: {
    en: 'Final Verdict',
    ja: '最終評決'
  },
  condition: {
    en: 'Condition',
    ja: '条件'
  },
  confidence: {
    en: 'Confidence',
    ja: '確信度'
  },

  // HighlightsV2Section
  keyHighlights: {
    en: 'Key Highlights',
    ja: '主要ハイライト'
  },
  tailwinds: {
    en: 'Tailwinds',
    ja: '追い風'
  },
  headwinds: {
    en: 'Headwinds',
    ja: '向かい風'
  },
  showDetails: {
    en: 'Show Details',
    ja: '詳細を表示'
  },
  hideDetails: {
    en: 'Hide Details',
    ja: '詳細を隠す'
  },
  whyItMatters: {
    en: 'Why It Matters',
    ja: '重要な理由'
  },
  context: {
    en: 'Context',
    ja: '背景'
  },
  timeBound: {
    en: 'Time-Bound',
    ja: '期限付き'
  },
  verified: {
    en: 'verified',
    ja: '検証済み'
  },
  estimated: {
    en: 'estimated',
    ja: '推定'
  },
  assumed: {
    en: 'assumed',
    ja: '想定'
  },

  // ProcessSection
  theProcess: {
    en: 'The Process',
    ja: 'プロセス'
  },
  recommendedPath: {
    en: 'Recommended Path',
    ja: '推奨パス'
  },
  keyTradeOffs: {
    en: 'Key Trade-offs',
    ja: '主要トレードオフ'
  },
  alternativesConsidered: {
    en: 'Alternatives Considered',
    ja: '検討された代替案'
  },
  pathAdvantages: {
    en: 'Path Advantages',
    ja: 'パスの利点'
  },
  testedInsights: {
    en: 'Tested Insights',
    ja: '検証済みインサイト'
  },
  acknowledgedRisks: {
    en: 'Acknowledged Risks',
    ja: '認識されたリスク'
  },
  severity: {
    en: 'Severity',
    ja: '深刻度'
  },
  showAllInsights: {
    en: 'Show All Insights',
    ja: '全てのインサイトを表示'
  },
  hideInsights: {
    en: 'Hide Insights',
    ja: 'インサイトを隠す'
  },

  // Failure actions
  pivot: {
    en: 'Pivot',
    ja: 'ピボット'
  },
  pass: {
    en: 'Pass',
    ja: 'パス'
  },
  reassess: {
    en: 'Reassess',
    ja: '再評価'
  }
};

export function t(key: keyof typeof translations, lang: Language): string {
  return translations[key][lang] || translations[key]['en'];
}

// Helper to format date based on language
export function formatDate(date: Date, lang: Language): string {
  if (lang === 'ja') {
    return date.toLocaleDateString('ja-JP', { year: 'numeric', month: 'long', day: 'numeric' });
  }
  return date.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
}

// Helper to format long date based on language
export function formatDateLong(date: Date, lang: Language): string {
  if (lang === 'ja') {
    return date.toLocaleDateString('ja-JP', { year: 'numeric', month: 'long', day: 'numeric' });
  }
  return date.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
}
