// UI translations for V2 Infographic components

export type Language = 'en' | 'ja';

export const translations = {
  // V2InfographicContainer
  executiveInfographic: {
    en: 'V2 Executive Infographic',
    ja: 'V2 エグゼクティブインフォグラフィック'
  },
  copyHtml: {
    en: 'Copy HTML',
    ja: 'HTMLをコピー'
  },
  downloadPdf: {
    en: 'Download as PDF',
    ja: 'PDFとしてダウンロード'
  },
  generatedBy: {
    en: 'Generated by The Olsenator V2',
    ja: 'The Olsenator V2 により生成'
  },

  // BannerSection
  stage: {
    en: 'Stage',
    ja: 'ステージ'
  },
  sector: {
    en: 'Sector',
    ja: 'セクター'
  },
  geography: {
    en: 'Geography',
    ja: '地域'
  },
  date: {
    en: 'Date',
    ja: '日付'
  },
  theVerdict: {
    en: 'The Verdict',
    ja: '結論'
  },
  thePrize: {
    en: 'The Opportunity',
    ja: '機会'
  },
  theRisk: {
    en: 'The Risk',
    ja: 'リスク'
  },
  theUnlock: {
    en: 'The Path',
    ja: '道筋'
  },
  go: {
    en: 'Go',
    ja: 'Go'
  },
  noGo: {
    en: 'No Go',
    ja: 'No Go'
  },
  conditionalGo: {
    en: 'Conditional Go',
    ja: '条件付きGo'
  },
  conditional: {
    en: 'Conditional',
    ja: '条件付き'
  },

  // NextStepsPathway
  nextSteps: {
    en: 'Next Steps',
    ja: '次のステップ'
  },
  phase1Validation: {
    en: 'Phase 1: Validation',
    ja: 'フェーズ1：検証'
  },
  phase2Execution: {
    en: 'Phase 2: Execution',
    ja: 'フェーズ2：実行'
  },
  ifAllGatesPass: {
    en: 'If All Gates Pass',
    ja: '全てのゲートを通過した場合'
  },
  successGate: {
    en: 'Success Gate',
    ja: '成功ゲート'
  },
  whatToDo: {
    en: 'What to do',
    ja: '実施内容'
  },
  unlocks: {
    en: 'Unlocks',
    ja: '解除される項目'
  },
  ifGateFails: {
    en: 'If Gate Fails',
    ja: 'ゲート失敗時'
  },
  venture: {
    en: 'venture',
    ja: 'ベンチャー'
  },
  joint: {
    en: 'joint',
    ja: '共同'
  },
  investor: {
    en: 'investor',
    ja: '投資家'
  },

  // ProcessSection
  pathSelectionAnalysis: {
    en: 'Path Selection Analysis',
    ja: '戦略パス選定分析'
  },
  comparativeSummary: {
    en: 'Comparative Summary',
    ja: '比較概要'
  },
  recommended: {
    en: 'Recommended',
    ja: '推奨'
  },
  
  // RIC Option Names
  option1StatusQuo: {
    en: 'Option 1: Status Quo',
    ja: 'オプション1：現状維持'
  },
  option1Description: {
    en: 'Continue operating exclusively as a Tier 1 System Integrator for physical engineering projects.',
    ja: '物理的エンジニアリングプロジェクトのTier 1システムインテグレーターとしての事業を継続。'
  },
  option2NarrowPlatform: {
    en: 'Option 2: Narrow Platform',
    ja: 'オプション2：ナロープラットフォーム'
  },
  option2Description: {
    en: 'Partnership-driven approach focusing on "triage" steps (Inspection and Design) via a "Concierge MVP" to validate demand.',
    ja: '「コンシェルジュMVP」で需要を検証する「トリアージ」ステップ（点検・設計）に集中した提携主導のアプローチ。'
  },
  option3EndToEnd: {
    en: 'Option 3: End-to-End Platform',
    ja: 'オプション3：エンドツーエンドプラットフォーム'
  },
  option3Description: {
    en: 'Build a comprehensive ecosystem covering the entire lifecycle from discovery to construction.',
    ja: '発見から建設まで全ライフサイクルを網羅する包括的エコシステムを構築。'
  },
  viewDetailsStrategy: {
    en: 'View Details & Strategy',
    ja: '詳細・戦略を見る'
  },
  viewAnalysis: {
    en: 'View Analysis',
    ja: '分析を見る'
  },
  whyRejected: {
    en: 'Why Not Selected',
    ja: '選定されなかった理由'
  },
  recommendation: {
    en: 'Recommendation',
    ja: '推奨方針'
  },
  strategy: {
    en: 'Strategy',
    ja: '戦略'
  },
  pros: {
    en: 'Pros',
    ja: 'メリット'
  },
  cons: {
    en: 'Cons',
    ja: 'デメリット'
  },
  rationale: {
    en: 'Rationale',
    ja: '根拠'
  },
  whenPreferred: {
    en: 'When This Option Would Be Preferred',
    ja: 'このオプションが選好される場合'
  },
  
  // Comparative Table Labels
  dimension: {
    en: 'Dimension',
    ja: '評価軸'
  },
  riskLevel: {
    en: 'Risk Level',
    ja: 'リスクレベル'
  },
  capitalRequired: {
    en: 'Capital Required',
    ja: '必要資本'
  },
  timeToValue: {
    en: 'Time to Value',
    ja: '価値実現までの時間'
  },
  keyStrength: {
    en: 'Key Strength',
    ja: '主要強み'
  },
  keyWeakness: {
    en: 'Key Weakness',
    ja: '主要弱点'
  },
  deRiskability: {
    en: 'De-riskability',
    ja: 'リスク軽減可能性'
  },
  
  // Option 1 (Status Quo) Content
  option1RiskLevel: {
    en: 'Low (Execution) / High (Strategic)',
    ja: '低（実行）／高（戦略）'
  },
  option1Capital: {
    en: '$0 incremental',
    ja: '追加投資なし'
  },
  option1TimeToValue: {
    en: 'Immediate',
    ja: '即時'
  },
  option1Strength: {
    en: 'Cash preservation',
    ja: 'キャッシュ保全'
  },
  option1Weakness: {
    en: 'Strategic obsolescence',
    ja: '戦略的陳腐化'
  },
  option1DeRisk: {
    en: 'High',
    ja: '高'
  },
  option1ModalTitle: {
    en: 'Option 1: Status Quo / No-Go',
    ja: 'オプション1：現状維持'
  },
  option1StrategyDetail: {
    en: 'Maintain Apex Infrastructure Services\' traditional business model, operating as a Tier 1 System Integrator focusing exclusively on physical engineering, fabrication, and construction (Steps 3–5). Rely on government-led digitalization initiatives rather than building proprietary technology.',
    ja: 'Apex Infrastructure Servicesの従来ビジネスモデルを維持し、物理的エンジニアリング、製造、建設（ステップ3〜5）に専念するTier 1システムインテグレーターとして運営。独自技術の構築ではなく、政府主導のデジタル化イニシアチブに依存。'
  },
  option1WhyNotSelected: {
    en: 'High strategic risk of commoditization as competitors like Nippon Koei digitize their service offerings. Fails to establish a new scalable profit center, leaving the company entirely dependent on cyclical construction bids.',
    ja: '日本工営のような競合がサービスをデジタル化する中、コモディティ化の戦略的リスクが高い。新たなスケーラブルな収益源を確立できず、循環的な建設入札に完全依存。'
  },
  option1WhenPreferred: {
    en: 'If AMC faces an immediate liquidity crisis requiring absolute cash preservation, or if MLIT explicitly mandates a single government-run platform that excludes private sector middleware.',
    ja: 'AMCが絶対的なキャッシュ保全を必要とする緊急の流動性危機に直面した場合、またはMLITが民間ミドルウェアを排除する単一の政府運営プラットフォームを明示的に義務付けた場合。'
  },
  
  // Option 2 (Narrow Platform) Content
  option2RiskLevel: {
    en: 'Medium',
    ja: '中'
  },
  option2Capital: {
    en: 'Moderate (Software + Ops)',
    ja: '中程度（ソフトウェア＋運用）'
  },
  option2TimeToValue: {
    en: 'Months (Concierge MVP)',
    ja: '数ヶ月（コンシェルジュMVP）'
  },
  option2Strength: {
    en: 'Hybrid Authority (License + Tech)',
    ja: 'ハイブリッド権限（免許＋技術）'
  },
  option2Weakness: {
    en: 'Procurement friction (OpEx)',
    ja: '調達摩擦（OpEx）'
  },
  option2DeRisk: {
    en: 'High (via Pilot)',
    ja: '高（パイロットにより）'
  },
  option2ModalTitle: {
    en: 'Option 2: Narrow Platform (Recommended)',
    ja: 'オプション2：ナロープラットフォーム（推奨）'
  },
  option2StrategyDetail: {
    en: 'Position Apex Infrastructure Services as the "triage" middleware between citizen reporting and professional repair. Partner with Urban Solutions Inc. (CityConnect) for data intake while focusing internal resources on converting raw citizen data into verified engineering work orders.',
    ja: 'Apex Infrastructure Servicesを市民通報と専門修繕の間の「トリアージ」ミドルウェアとして位置付け。Urban Solutions Inc.（CityConnect）と提携してデータ取得を行い、内部リソースは生の市民データを検証済みエンジニアリング作業指示に変換することに集中。'
  },
  option2RationaleIntro: {
    en: 'This option is recommended based on three key factors:',
    ja: 'このオプションは以下の3つの主要因に基づき推奨されます：'
  },
  option2Rationale1Title: {
    en: 'Competitive Moat',
    ja: '競争優位性'
  },
  option2Rationale1Detail: {
    en: 'Uses Apex Infrastructure Services\' legal licensure to certify safety, a capability that pure software competitors cannot replicate due to liability constraints.',
    ja: 'Apex Infrastructure Servicesの法的免許を活用して安全性を認証。純粋なソフトウェア競合は責任制約により再現不可能な能力。'
  },
  option2Rationale2Title: {
    en: 'Capital Efficiency',
    ja: '資本効率'
  },
  option2Rationale2Detail: {
    en: 'The "Concierge MVP" approach validates municipal willingness-to-pay within 6 months using manual processes, avoiding the 3.5-year development timeline required for a full marketplace.',
    ja: '「コンシェルジュMVP」アプローチにより、手動プロセスを用いて6ヶ月以内に自治体の支払い意思を検証。フルマーケットプレイスに必要な3.5年の開発期間を回避。'
  },
  option2Rationale3Title: {
    en: 'Market Fit',
    ja: '市場適合性'
  },
  option2Rationale3Detail: {
    en: 'Directly addresses the municipal labor shortage by automating the filtering of citizen reports, solving the "digital inbox" overflow that currently prevents government adoption.',
    ja: '市民通報のフィルタリングを自動化することで自治体の人手不足に直接対処。現在政府導入を妨げている「デジタル受信箱」の氾濫問題を解決。'
  },
  option2ConsDetail: {
    en: 'Creates dependency on Urban Solutions Inc. for the data funnel. Procurement friction remains a risk as municipalities may face challenges paying for OpEx subscription services.',
    ja: 'データファネルにおいてUrban Solutions Inc.への依存が生じる。自治体がOpExサブスクリプションサービスへの支払いに課題を抱える可能性があり、調達摩擦がリスクとして残る。'
  },
  
  // Option 3 (End-to-End) Content
  option3RiskLevel: {
    en: 'High',
    ja: '高'
  },
  option3Capital: {
    en: 'Massive Capital',
    ja: '大規模資本'
  },
  option3TimeToValue: {
    en: '>3.5 years',
    ja: '3.5年超'
  },
  option3Strength: {
    en: 'Total Lifecycle Ownership',
    ja: '全ライフサイクル所有'
  },
  option3Weakness: {
    en: 'Legal/Regulatory barriers',
    ja: '法的・規制上の障壁'
  },
  option3DeRisk: {
    en: 'Low',
    ja: '低'
  },
  option3ModalTitle: {
    en: 'Option 3: Full End-to-End Platform',
    ja: 'オプション3：フルエンドツーエンドプラットフォーム'
  },
  option3StrategyDetail: {
    en: 'Develop a comprehensive operating system managing the entire infrastructure maintenance lifecycle from Step 1 (Discovery) through Step 5 (Construction). Build a "System of Record" integrating citizen reporting, engineering analysis, and a digital marketplace for procurement.',
    ja: 'ステップ1（発見）からステップ5（建設）までインフラ保守の全ライフサイクルを管理する包括的オペレーティングシステムを開発。市民通報、エンジニアリング分析、調達用デジタルマーケットプレイスを統合した「記録システム」を構築。'
  },
  option3WhyNotSelected: {
    en: 'Japanese law prohibits the same entity from managing both design and construction bidding (separation of duties), making an integrated marketplace legally inviable. Requires "massive capital" and a development timeline exceeding 3.5 years.',
    ja: '日本の法律は同一事業体が設計と建設入札の両方を管理することを禁止しており（職務分離）、統合マーケットプレイスは法的に実現不可能。「大規模資本」と3.5年を超える開発期間が必要。'
  },
  option3WhenPreferred: {
    en: 'If Japanese construction laws are amended to allow design-build integration within digital platforms, or if AMC acquires a major software company with existing marketplace infrastructure and user base.',
    ja: 'デジタルプラットフォーム内での設計・建設統合を許可するよう日本の建設法が改正された場合、またはAMCが既存のマーケットプレイスインフラとユーザーベースを持つ大手ソフトウェア企業を買収した場合。'
  },
  option3ProsDetail: {
    en: 'Total lifecycle ownership creates high switching costs and network effects, establishing a defensive moat against large IT competitors.',
    ja: '全ライフサイクル所有により高いスイッチングコストとネットワーク効果を創出し、大手IT競合に対する防御的な堀を構築。'
  },
  
  // Engagement Model (kept for Option 2)
  recommendedEngagementModel: {
    en: 'Recommended Engagement Model',
    ja: '推奨関与モデル'
  },
  leadUnit: {
    en: 'Lead Unit',
    ja: '主担当'
  },
  leadUnitDetail: {
    en: 'New Business Planning & Strategy Division acts as the "Venture Lead," responsible for the platform business model.',
    ja: '新規事業企画・戦略部門が「ベンチャーリード」としてプラットフォーム事業モデルを担う。'
  },
  domainExpert: {
    en: 'Domain Expert',
    ja: 'ドメイン専門家'
  },
  domainExpertDetail: {
    en: 'Apex Infrastructure Services acts as the "Technical Anchor," defining the inspection protocols (Steps 2–3).',
    ja: 'Apex Infrastructure Servicesが「技術アンカー」として点検プロトコル（ステップ2〜3）を定義。'
  },
  orchestrationRole: {
    en: 'Orchestration Role',
    ja: 'オーケストレーション役'
  },
  orchestrationRoleDetail: {
    en: 'AMC functions as the Platform Orchestrator, managing the data flow between citizens, municipalities, and external contractors.',
    ja: 'AMCがプラットフォーム・オーケストレーターとして、市民・自治体・外部事業者間のデータ流通を統括。'
  },

  // StrategicFitSection
  strategicFitAssessment: {
    en: 'Strategic Fit Assessment',
    ja: '戦略的適合性評価'
  },
  strategicAttractiveness: {
    en: 'Strategic Attractiveness',
    ja: '戦略的魅力度'
  },
  executionCapability: {
    en: 'Execution Capability',
    ja: '実行力'
  },
  capitalInfrastructure: {
    en: 'Capital & Infrastructure',
    ja: '資本・インフラ'
  },
  priorityAlignment: {
    en: 'Priority Alignment',
    ja: '優先事項の整合性'
  },
  strategicPosition: {
    en: 'Strategic Position',
    ja: '戦略的位置付け'
  },
  high: {
    en: 'High',
    ja: '高'
  },
  low: {
    en: 'Low',
    ja: '低'
  },
  executionAxis: {
    en: 'Execution',
    ja: '実行力'
  },
  capableButUninteresting: {
    en: 'Capable but\nUninteresting',
    ja: '実行可能だが魅力に欠ける'
  },
  highValueOpportunity: {
    en: 'High Value\nOpportunity',
    ja: '高価値の機会'
  },
  avoid: {
    en: 'Avoid',
    ja: '回避'
  },
  strategicButRisky: {
    en: 'Strategic\nbut Risky',
    ja: '戦略的だがリスク高'
  },
  thisVenture: {
    en: 'This Venture',
    ja: '本件'
  },
  shouldWeDoIt: {
    en: 'Should We Do It?',
    ja: '実施すべきか？'
  },
  canWeDoIt: {
    en: 'Can We Do It?',
    ja: '実施可能か？'
  },
  thePrizeLabel: {
    en: 'The Opportunity',
    ja: '機会'
  },
  strategicFit: {
    en: 'Strategic Fit',
    ja: '戦略的適合性'
  },
  ourEdge: {
    en: 'Our Edge',
    ja: '競争優位性'
  },
  capital: {
    en: 'Capital',
    ja: '資本'
  },
  marketAccess: {
    en: 'Market Access',
    ja: '市場アクセス'
  },
  people: {
    en: 'People',
    ja: '人材'
  },
  marketSize: {
    en: 'Market Size',
    ja: '市場規模'
  },
  margins: {
    en: 'Margins',
    ja: '利益率'
  },
  durability: {
    en: 'Durability',
    ja: '持続性'
  },
  bottomLine: {
    en: 'Bottom Line',
    ja: '結論'
  },
  betType: {
    en: 'Bet Type',
    ja: '投資タイプ'
  },
  portfolioFit: {
    en: 'Portfolio Fit',
    ja: 'ポートフォリオ適合性'
  },
  policyAlignment: {
    en: 'Policy Alignment',
    ja: '政策整合性'
  },
  unfairAdvantages: {
    en: 'Unfair Advantages',
    ja: '圧倒的優位性'
  },
  whyUs: {
    en: 'Why Us',
    ja: 'なぜ我々か'
  },
  cashPosition: {
    en: 'Cash Position',
    ja: 'キャッシュポジション'
  },
  facilities: {
    en: 'Facilities',
    ja: '施設'
  },
  toolsSystems: {
    en: 'Tools & Systems',
    ja: 'ツール＆システム'
  },
  customerRelationships: {
    en: 'Customer Relationships',
    ja: '顧客関係'
  },
  geographicPresence: {
    en: 'Geographic Presence',
    ja: '地理的プレゼンス'
  },
  regulatoryExperience: {
    en: 'Regulatory Experience',
    ja: '規制対応経験'
  },
  skills: {
    en: 'Skills',
    ja: 'スキル'
  },
  experience: {
    en: 'Experience',
    ja: '経験'
  },
  bandwidth: {
    en: 'Bandwidth',
    ja: 'リソース余力'
  },
  verdict: {
    en: 'Verdict',
    ja: '評決'
  },
  yes: {
    en: 'Yes',
    ja: 'はい'
  },
  no: {
    en: 'No',
    ja: 'いいえ'
  },
  borderline: {
    en: 'Borderline',
    ja: '境界線上'
  },
  medium: {
    en: 'Medium',
    ja: '中'
  },
  synthesis: {
    en: 'Synthesis',
    ja: '総括'
  },
  alignment: {
    en: 'Alignment',
    ja: '整合性'
  },
  divergence: {
    en: 'Divergence',
    ja: '乖離点'
  },
  gapToClose: {
    en: 'Gap to Close',
    ja: '埋めるべきギャップ'
  },
  finalVerdict: {
    en: 'Final Verdict',
    ja: '最終評決'
  },
  condition: {
    en: 'Condition',
    ja: '条件'
  },
  confidence: {
    en: 'Confidence',
    ja: '確信度'
  },

  // HighlightsV2Section
  keyHighlights: {
    en: 'Key Highlights',
    ja: '主要ハイライト'
  },
  tailwinds: {
    en: 'Tailwinds',
    ja: '追い風'
  },
  headwinds: {
    en: 'Headwinds',
    ja: '向かい風'
  },
  showDetails: {
    en: 'Show Details',
    ja: '詳細を表示'
  },
  hideDetails: {
    en: 'Hide Details',
    ja: '詳細を隠す'
  },
  whyItMatters: {
    en: 'Why It Matters',
    ja: '重要な理由'
  },
  context: {
    en: 'Context',
    ja: '背景'
  },
  timeBound: {
    en: 'Time-Bound',
    ja: '期限付き'
  },
  verified: {
    en: 'verified',
    ja: '検証済み'
  },
  estimated: {
    en: 'estimated',
    ja: '推定'
  },
  assumed: {
    en: 'assumed',
    ja: '想定'
  },

  // ProcessSection
  theProcess: {
    en: 'The Process',
    ja: 'プロセス'
  },
  recommendedPath: {
    en: 'Recommended Path',
    ja: '推奨パス'
  },
  keyTradeOffs: {
    en: 'Key Trade-offs',
    ja: '主要トレードオフ'
  },
  alternativesConsidered: {
    en: 'Alternatives Considered',
    ja: '検討された代替案'
  },
  pathAdvantages: {
    en: 'Path Advantages',
    ja: 'パスの利点'
  },
  testedInsights: {
    en: 'Tested Insights',
    ja: '検証済みインサイト'
  },
  acknowledgedRisks: {
    en: 'Acknowledged Risks',
    ja: '認識されたリスク'
  },
  severity: {
    en: 'Severity',
    ja: '深刻度'
  },
  showAllInsights: {
    en: 'Show All Insights',
    ja: '全てのインサイトを表示'
  },
  hideInsights: {
    en: 'Hide Insights',
    ja: 'インサイトを隠す'
  },

  // Failure actions
  pivot: {
    en: 'Pivot',
    ja: 'ピボット'
  },
  pass: {
    en: 'Pass',
    ja: 'パス'
  },
  reassess: {
    en: 'Reassess',
    ja: '再評価'
  }
};

export function t(key: keyof typeof translations, lang: Language): string {
  return translations[key][lang] || translations[key]['en'];
}

// Helper to format date based on language
export function formatDate(date: Date, lang: Language): string {
  if (lang === 'ja') {
    return date.toLocaleDateString('ja-JP', { year: 'numeric', month: 'long', day: 'numeric' });
  }
  return date.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
}

// Helper to format long date based on language
export function formatDateLong(date: Date, lang: Language): string {
  if (lang === 'ja') {
    return date.toLocaleDateString('ja-JP', { year: 'numeric', month: 'long', day: 'numeric' });
  }
  return date.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
}
